sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - main
notifications:
  email: false
node_js:
  - 16.13.1
before_install:
  - npm i -g npm@8.1.2
before_script:
  - npm prune
script:
  - npm run test
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release
